name: Rust CICD

on: ["push", "pull_request"]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cargo-bins/cargo-binstall@main
      - uses: Swatinem/rust-cache@v2
      - name: Install espup
        run: cargo +stable binstall --no-confirm espup && espup install
      - name: Cargo Build
        run: source $HOME/export-esp.sh && cargo build --verbose
      - name: Clippy
        run: source $HOME/export-esp.sh && cargo clippy --all-targets --all-features

